apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # 자신의 이메일 주소 입력
    email: woosung81.lee@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    # 웹 서버를 이용하여 검증을 진행하는 http01 solver 사용 
    solvers:
    - http01:
        # k3s의 기본 Ingress 컨트롤러인 traefik을 사용하도록 설정
        ingress:
          class: traefik
